// File: dual_port_ram.v
// Generated by MyHDL 0.11
// Date: Tue Nov 24 12:01:47 2020


`timescale 1ns/10ps

module dual_port_ram (
    clk_i,
    wr_i,
    wr_addr_i,
    rd_addr_i,
    data_i,
    data_o
);


input clk_i;
input wr_i;
input [7:0] wr_addr_i;
input [7:0] rd_addr_i;
input [7:0] data_i;
output [7:0] data_o;
reg [7:0] data_o;

reg [7:0] mem [0:256-1];



always @(posedge clk_i) begin: DUAL_PORT_RAM_LOC_INSTS_CHUNK_INSTS_K
    if (wr_i) begin
        mem[wr_addr_i] <= data_i;
    end
    data_o <= mem[rd_addr_i];
end

endmodule
