#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 23 21:23:14 CET 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim blinker_func_synth -key {Post-Synthesis:sim_1:Functional:blinker} -tclbatch blinker.tcl -log simulate.log"
xsim blinker_func_synth -key {Post-Synthesis:sim_1:Functional:blinker} -tclbatch blinker.tcl -log simulate.log

